### ISSUE TITLE
Needs a licence

### ISSUE THREAD

**Issue by chrisseaton** [jruby/rubybench#1]
I can't find any licence information in this repository. If it's the JRuby licence, because it was forked from there, could that be made explicit? But I'm not sure it's that simple. For example time/bench_richards.rb states that it's taken from http://flwrpwr.free.fr/Ruby/bench/bench27.rb, but there's no licence information there either, so I don't know if the original author imported it, or someone copied the file, added that attribution line and thought that was enough.

**Comment by headius** [comment]
I think going with EPL, JRuby's most permissive license, would be just fine.

**Comment by eregon** [comment]
Sounds good.

**Comment by chrisseaton** [comment]
@eregon on #2 "About #1, I feel it is not so easy as I would like to bring benchmarks from many sources including JRuby, MRI, Rubinius and others."

You could add a licence header to each file, or keep them in separate directories with a licence file in each, so the benchmarks from JRuby get the JRuby licence, the ones from MRI get that licence, the Rubinius ones get that licence - that shouldn't be a problem.

You would need to figure out what the copyright is on files like time/bench_richards.rb - this file has been copied from somewhere but lost its licence information. Do you have permission to be distributing it? I'm sure you do, but it needs to be written down somewhere who the copyright holder is and under what licence they are letting you use it. I tried emailing the Phil mentioned at flwrpwr.free.fr, but got no response. Maybe someone in the JRuby community knows who he is.

At the moment I'd like to use these benchmarks, but nobody can unless they have an agreement with you because there is no licence permission to do so. It's great that you've put it on GitHub, but without a licence most people won't be able to use it.

**Comment by eregon** [comment]
Waiting an answer from the MRI team, but Rubinius and JRuby guys already agreed for MIT or BSD.
